from permutation_group_library.permutation import Permutation
from permutation_group_library.permutation_group import Permutation_Group
import itertools


def list_contains_item(input_list, item):
    for a in input_list:
        if a == item:
            return True
    return False


def generate_single_cycle_permutations_of_shape(max_element, element_count):
    itertool_list = [list(p) for p in itertools.permutations(range(1, max_element + 1), element_count)]
    output_list = []

    for p in itertool_list:
        perm = Permutation([p])
        if not list_contains_item(output_list, perm):
            output_list.append(perm)

    return output_list

# this function is not used in this specific search, but was used in other similar searches I did
def generate_2_2_cycles(max_element):
    itertool_list = [list(p) for p in itertools.permutations(range(1, max_element + 1), 4)]
    output_list = []

    for p in itertool_list:
        perm = Permutation([p[:2], p[2:]])
        if not list_contains_item(output_list, perm):
            output_list.append(perm)

    return output_list


if __name__ == "__main__":
    #In its current form, this code searches for the number of subgroups of S_5 of order 12 generate by three 2-cycles
    s_5_2_cycles = generate_single_cycle_permutations_of_shape(5, 2)

    target_groups = []
    
    for i in range(len(s_5_2_cycles)):
        c1 = s_5_2_cycles[i]
        for j in range(i + 1, len(s_5_2_cycles)):
            c2 = s_5_2_cycles[j]
            for k in range(j + 1, len(s_5_2_cycles)):
                c3 = s_5_2_cycles[k]
                group = Permutation_Group([c1, c2, c3])
                if group.order == 12:
                    if not list_contains_item(target_groups, group):
                        print(f"Group of order 12 generated by {c1}, {c2}, and {c3}")
                        target_groups.append(group)
    
    print(f"Found {len(target_groups)} groups of order 12")
    #Sample output:
        # Group of order 12 generated by (1,2), (1,3), and (4,5)
        # Group of order 12 generated by (1,2), (1,4), and (3,5)
        # Group of order 12 generated by (1,2), (1,5), and (3,4)
        # Group of order 12 generated by (1,2), (3,4), and (3,5)
        # Group of order 12 generated by (1,3), (1,4), and (2,5)
        # Group of order 12 generated by (1,3), (1,5), and (2,4)
        # Group of order 12 generated by (1,3), (2,4), and (2,5)
        # Group of order 12 generated by (1,4), (1,5), and (2,3)
        # Group of order 12 generated by (1,4), (2,3), and (2,5)
        # Group of order 12 generated by (1,5), (2,3), and (2,4)
        # Found 10 groups of order 12